export const mockTreeData = {
  success: true,
  code: 200,
  msg: "操作成功",
  data: [
    {
      id: "13",
      code: "1",
      name: "集团",
      pCode: "0",
      level: 1,
      status: 1,
      remark: null,
      children: [
        {
          id: "14",
          code: "1-1",
          name: "事业本部",
          pCode: "1",
          level: 2,
          status: 1,
          remark: null,
          children: [
            {
              id: "16",
              code: "1-1-1",
              name: "事业一部",
              pCode: "1-1",
              level: 3,
              status: 1,
              remark: null,
              children: null,
            },
            {
              id: "17",
              code: "1-1-2",
              name: "事业二部",
              pCode: "1-1",
              level: 3,
              status: 1,
              remark: null,
              children: null,
            },
            {
              id: "18",
              code: "1-1-3",
              name: "事业三部",
              pCode: "1-1",
              level: 3,
              status: 1,
              remark: null,
              children: null,
            },
          ],
        },
        {
          id: "15",
          code: "1-2",
          name: "零担事业本部",
          pCode: "1",
          level: 2,
          status: 1,
          remark: null,
          children: [
            {
              id: "19",
              code: "1-2-1",
              name: "深圳经营战区",
              pCode: "1-2",
              level: 3,
              status: 1,
              remark: null,
              children: null,
            },
          ],
        },
      ],
    },
  ],
};
